# Generated by Django 2.2.5 on 2021-06-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='公文标题')),
                ('office', models.CharField(max_length=50, verbose_name='发文机关')),
                ('person', models.CharField(max_length=20, verbose_name='上传者')),
                ('Classification', models.BooleanField(default=False, verbose_name='是否涉密')),
                ('time', models.DateField(verbose_name='上传时间')),
                ('img', models.FileField(upload_to='documentImg/', verbose_name='公文缩略图')),
                ('file', models.FileField(upload_to='documentFile/', verbose_name='公文文件')),
            ],
            options={
                'verbose_name': '公文信息',
                'verbose_name_plural': '公文信息',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=20, verbose_name='分类标签')),
            ],
            options={
                'verbose_name': '公文分类',
                'verbose_name_plural': '公文分类',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('plays', models.IntegerField(default=0, verbose_name='查看次数')),
                ('search', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('download', models.IntegerField(default=0, verbose_name='下载次数')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Document', verbose_name='歌名')),
            ],
            options={
                'verbose_name': '公文动态',
                'verbose_name_plural': '公文动态',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Label', verbose_name='公文分类'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('text', models.CharField(max_length=500, verbose_name='内容')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Document', verbose_name='公文名')),
            ],
            options={
                'verbose_name': '公文批复',
                'verbose_name_plural': '公文批复',
            },
        ),
    ]
