# Generated by Django 2.2.5 on 2021-06-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Document', verbose_name='公文标题'),
        ),
    ]
