# Generated by Django 2.2.5 on 2021-06-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210601_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='公文类型'),
        ),
    ]
