# Generated by Django 2.2.5 on 2021-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lyrics',
            field=models.FileField(blank=True, default='暂无歌词', upload_to='documentLyric/', verbose_name='歌词'),
        ),
    ]
