# Generated by Django 2.2.5 on 2021-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210602_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key',
            field=models.CharField(default='', max_length=30, verbose_name='公文密钥'),
        ),
    ]
