# Generated by Django 2.2.5 on 2021-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_document_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='key',
            field=models.BinaryField(default=b'', max_length=200, verbose_name='公文密钥'),
        ),
    ]
